#
# GNUmakefile for target TestLibrary
# begin - generated by buildtool
#

include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME= TestLibrary

TestLibrary_OBJC_FILES = TestLibrary/TestLibrary.m 

TestLibrary_C_FILES = 

TestLibrary_CPP_FILES = 

TestLibrary_OBJCPP_FILES = 

TestLibrary_HEADER_FILES = TestLibrary/TestLibrary.h

TestLibrary_RESOURCE_FILES = 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./TestLibrary 

ADDITIONAL_OBJC_LIBS += 

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/library.make

#
# end - generated makefile
#
